# kubectl get pods -l purpose=demonstrate-envars
# kubectl exec envar-demo -- printenv
apiVersion: v1
kind: Pod
metadata:
  name: fastapi-ml
  labels:
    app: fastapi-ml
spec:
  containers:
    - image: anirill/online_inference:v1
      name: fastapi-ml
      ports:
        - containerPort: 8000
