apiVersion: v1
kind: Pod
spec:
  containers:
    - name: probes
      image: anirill/online_inference:v2
      ports:
        - containerPort: 8080
      readynessProbe:
        httpGet:
          path: /healthz
          port: 8080
        initialDelaySeconds: 15
        periodSeconds: 3
      livenessProbe:
        httpGet:
          path: /healthz
          port: 8080
          httpHeaders:
          - name: Custom-Header
            value: Awesome
        initialDelaySeconds: 30
        periodSeconds: 3
