apiVersion: v1
kind: Pod
metadata:
  name: pod-probes
  labels:
    app: online-inference
spec:
  containers:
    - name: pod-probes
      image: anirill/online_inference:v2
      ports:
        - containerPort: 8000
      readinessProbe:
        httpGet:
          path: /healthz
          port: 8000
        initialDelaySeconds: 15
        periodSeconds: 3
      livenessProbe:
        httpGet:
          path: /healthz
          port: 8000
        initialDelaySeconds: 30
        periodSeconds: 3
