version: 1
formatters:
    simple:
        class: logging.Formatter
        format: "%(asctime)s %(name)s %(levelname)s %(message)s"
        datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
    file_handler:
        class: logging.FileHandler
        filename: inverted_index.log
        level: DEBUG
        formatter: simple
    stream_handler:
        class: logging.StreamHandler
        stream: ext://sys.stderr
        level: INFO
        formatter: simple
loggers:
    task_Klestov_Andrei_inverted_index:
        level: DEBUG
        handlers: [file_handler]
        propagate: yes
root:
    level: DEBUG
    handlers: [stream_handler]