input_data_path: "../data/heart.csv"
model_path: "../models/model.pkl"
metric_path: "../models/metrics.json"
splitting_params:
  val_size: 0.2
  random_state: 42
train_params:
  model_type: "LogisticRegression"
  model_param:
    solver: "saga"
    penalty: "l1"
    max_iter: 100
    tol: 0.0001
    C: 0.2
feature_params:
  target_col: "target"

